apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: speedtest
            image: gfechio/speedtest:armv7
          restartPolicy: OnFailure
